### ISSUE TITLE
unsupported version 1_19_R1

### ISSUE THREAD

**Issue by DasShorty** [upperlevel/spigot-anvil-gui#3]
Hey,

i got this error if i run my plugin in paper 1.19. 
i had downloaded the latest version from paper. Can you please fix this? :)

the error can you find here -> https://www.toptal.com/developers/hastebin/rarahorohe.yaml

**Comment by SnowyCoder** [comment]
Hello, I didn't know anyone was still using this, I could fix this bug but I haven't worked on this project since 2015, why don't you use https://github.com/WesJD/AnvilGUI, it seems better maintained

**Comment by DasShorty** [comment]
I switched to this repo because the repo from WesJD didn't work in the 1.19 😕

**Comment by SnowyCoder** [comment]
I'm sorry, this is quite a time-consuming task as I would need to reverse-engineer the strange spigot choices and find back all of the function names. The other option is to go complain to bukkit/spigot's developers until they merge an officially maintained anvil API, this would be even more time consuming.
Right now it's just better to concentrate development to a single project, so I'd suggest opening an issue on WesJD's project.
